### ISSUE TITLE
assigning variable with function not working?

### ISSUE THREAD

**Issue by Attacler** [jonschlinkert/eval-estree-expression#4]
code:
`"use strict";

const start = Date.now();
process.on("exit", () => console.log("Time: " + Date.now() - start + "ms"));

const { evaluate } = require("eval-estree-expression");
const { parse } = require("esprima");
const axios = require("axios");

const logs = [];
const context = {
  getRecord: async function (id) {
    return (await axios("http://httpbin.org/get")).data;
  },
  console: {
    log(...data) {
      logs.push(data);
    },
  },
};

// const { evaluate } = require("eval-estree-expression");
const input = `
const rec = getRecord(1);
console.log(rec);
`;
const ast = parse(input).body[0].expression;
// const tree = parse("[" + input + "]");

evaluate(ast, context, { functions: true })
  .then((...e) => {
    console.log(e);
    console.log(logs);
  })
  .catch(console.error);
`

Error:
TypeError: Cannot read property 'parent' of undefined
    at Expression.visit (C:\Users\bartd\Nextcloud\Algemeen\Development\Workflows\DATFAflow\node_modules\eval-estree-expression\lib\ExpressionSync.js:35:58)
    at Expression.evaluate (C:\Users\bartd\Nextcloud\Algemeen\Development\Workflows\DATFAflow\node_modules\eval-estree-expression\lib\Expression.js:18:17)
    at evaluate (C:\Users\bartd\Nextcloud\Algemeen\Development\Workflows\DATFAflow\node_modules\eval-estree-expression\lib\Expression.js:14:42)
    at Object.<anonymous> (C:\Users\bartd\Nextcloud\Algemeen\Development\Workflows\DATFAflow\testsBackend.js:30:1)

**Comment by jonschlinkert** [comment]
Variable assignment isn't supported. This is mentioned on [the readme](https://github.com/jonschlinkert/eval-estree-expression#operators), but we could probably make it more prominent.
