### ISSUE TITLE
 Cannot find module 'util'

### ISSUE THREAD

**Issue by patrickmatte** [jonschlinkert/eval-estree-expression#7]
Does this only work on nodejs? I'm getting an error while trying to compile.

Uncaught Error: Cannot find module 'util'
    at webpackMissingModule (content.js:11081:83)
    at ../node_modules/eval-estree-expression/lib/inspect.js (content.js:11081:162)
    at __webpack_require__ (content.js:22203:41)
    at ../node_modules/eval-estree-expression/lib/ExpressionSync.js (content.js:10316:17)
    at __webpack_require__ (content.js:22203:41)
    at ../node_modules/eval-estree-expression/lib/Expression.js (content.js:10109:24)
    at __webpack_require__ (content.js:22203:41)
    at ../node_modules/eval-estree-expression/index.js (content.js:10095:18)
    at __webpack_require__ (content.js:22203:41)

**Comment by jonschlinkert** [comment]
Closing since this was resolved by https://github.com/jonschlinkert/eval-estree-expression/commit/7dfb70c5ccf0b623beb1dd9d396cb5a817ecdfb9.
